# permissions for end users to view jsonservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: json-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: jsonserver-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - jsonservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - jsonservers/status
  verbs:
  - get
