apiVersion: example.com/v1
kind: JsonServer
metadata:
  name: my-server
  namespace: default
spec:
  replicas: 1
  jsonConfig: |
    {
      "people": [
        {
          "id": 1,
          "name": "Person A"
        },
        {
          "id": 2,
          "name": "Person B"
        }
      ]
    }