apiVersion: example.com/v1
kind: JsonServer
metadata:
  name: app-my-server
spec:
  jsonConfig: |
    {
      "people": [
        {
          "id": 1,
          "name": "Person A"
        },
        {
          "id": 2,
          "name": "Person B"
        }
      ]
    }