apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: json-server-opearator
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart/
    repoURL: https://github.com/kklysenko/json-server-operator